### ISSUE TITLE
2.singleaccount CSR deployment failure

### ISSUE THREAD

**Issue by carter3d** [geseib/tgwwalk#7]
Unable to deploy the CSR.  Must first subscribe in the marketplace: https://aws.amazon.com/marketplace/pp/B00NF48FI2/

Also, c5.large is not a valid option after I subscribed in the marketplace.  c4.large is one of the valid choices.

**Comment by geseib** [comment]
Verify if Instructions [here](https://networkshopdev.aws.seibtribe.com/15-prerequisites.html).

**Comment by carter3d** [comment]
Looks good.  Thank you.
